### ISSUE TITLE
How to model propagation between threads within a process (address space)

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#41]
From EMV2 Standard document
a process, thread group, or thread to every other process, thread group, or thread that is bound to any common virtual processor, processor or memory (Note that address space boundary is enforced at the process level, i.e., two threads inside the same process may affect each other beyond the specified error propagation points). 

How to model propagations across threads inside an address space (process)?
Via binding to virtual processor or processor
Implicit or explicit at thread/process level
Naming of propagation point
Specification of error types being propagated

**Comment by buzden** [comment]
Personally I think that error propagating from one thread to another through (shared) memory of a process
- are not thread-level, i.e. should be considered at the process level (or upper when the reason is in OS, for example);
- should be explicit (or at least should have an ability to be defined explicitly);
- is (in general) similar to errors propagating from one process to another through data accesses; thus perhaps should have similar ways of expressing them in the error model.

**Comment by reteprelief** [comment]
We identified several ways of dealing with this:
1) threads share a resource, thus the resource binding will take care of the problem
2) use user defined propagation paths
3) introduce error events that reflect the effects from other threads
4) built in: fault impact and fault tree generators know about it

**Comment by jjhugues** [comment]
The question has an answer that does not require updates to the document itself
